[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/go-resty/resty"
  version = "1.9.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/olekukonko/tablewriter"
  revision = "be2c049b30ccd4d3fd795d6bf7dce74e42eeedaa"
